# Generated by Django 4.0.1 on 2022-01-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weather_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='id',
        ),
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
