version: '3.9'

services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=bl_weather_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8080:8000"
    volumes:
      - .:/app
    depends_on:
      - db


volumes:
  postgres_data: